run: BirthdayPresentsParty.java
	javac BirthdayPresentsParty.java;
	java -ea BirthdayPresentsParty
	rm *.class;

verbose: BirthdayPresentsParty.java
	javac BirthdayPresentsParty.java;
	java -ea BirthdayPresentsParty -verbose
	rm *.class;
