run: BirthdayPresentsParty.java
	javac BirthdayPresentsParty.java;
	java BirthdayPresentsParty
	rm *.class;

verbose: BirthdayPresentsParty.java
	javac BirthdayPresentsParty.java;
	java BirthdayPresentsParty -verbose
	rm *.class;
